### ISSUE TITLE
Issues with google chrome

### ISSUE THREAD

**Issue by samuel9554** [IDT-media/mobiledetect#1]
Hi I don't know why but with the new version of google chrome the plugin is thinking I have a mobile but i'm on a computer the last time I check it was working now is won't work anymore on google chrome I check with internet explorer and is still work.
{$device->type} show Phone in google chrome

Can you help

**Comment by uniqu3** [comment]
Should be fixed with Mobile_Detect 2.8.12 Class, which is commited now

**Comment by samuel9554** [comment]
Thank for the quick fix
